### ISSUE TITLE
Automatically or manually?

### ISSUE THREAD

**Issue by openncomp** [nanego/redmine_auto_update_status#5]
Greetings!
Thank you for a very useful plugin!
Do I understand correctly that it should automatically perform the actions specified in the rules without the user's participation?

This is not happening for me.
The rules collect tasks that fit the conditions, but no action is performed automatically.

I have to manually press each time:"Apply to all issues". 

Maybe I missed something?

**Comment by openncomp** [comment]
I figured it out!
To automatically update statuses, you need to make a script and run it with a cron.

```
#!/bin/bash -

source /usr/local/rvm/scripts/rvm
cd /opt/redmine/
bundle exec rake redmine:auto_update_status:apply_rules RAILS_ENV=production
```

**Comment by nanego** [comment]
Exactly. Sorry I missed your initial message.
I will add this sample code in the Readme file.
