### ISSUE TITLE
May I ask how to install your plugin?

### ISSUE THREAD

**Issue by dzzrit** [nanego/redmine_auto_update_status#6]
![QQ截图20230725195713](https://github.com/nanego/redmine_auto_update_status/assets/139627296/a1634722-34d6-4b35-bb62-2a60bd6bfc31)

Hello, I have downloaded several of your plugins, and some of them always prompt errors. I don't know how to install them correctly. I put the plugins in the folder and restart them, but they cannot be used. Even if I try rake mode, they cannot be used

**Comment by nanego** [comment]
Hello. The plugin might not have been compatible with Redmine 5 when you last tried it. If you could test the latest version and let us know if everything works smoothly, it would be greatly appreciated. Thank you.
